project:
  type: website
  output-dir: "."

website:
  title: "Liam Turner"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: R Baiscs
        href: danl-200-quarto.qmd
      - text: Blog
        href: blog-listing.qmd
            
  page-footer: 
    center: "Powered with GitHub and Quarto<br>Â© Liam Turner, 2024"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
